{{- if .Values.ontrack.application_yaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ontrack.fullname" . }}-application
data:
  application.yaml: |-
    {{- toYaml .Values.ontrack.application_yaml | nindent 4 }}
{{- end }}
