{{- if and .Values.ontrack.casc.enabled .Values.casc -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ontrack.fullname" . }}-casc
data:
  casc.yaml: |-{{ .Values.casc | toYaml | nindent 4 }}
{{- end -}}
