apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ontrack.fullname" . }}
  labels:
    {{- include "ontrack.labels" . | nindent 4 }}
spec:
  serviceName: ontrack
  selector:
    matchLabels:
      {{- include "ontrack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ontrack.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ontrack.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      {{- if .Values.extraContainers }}
        {{- toYaml .Values.extraContainers | nindent 8 }}
      {{- end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: ontrack
              mountPath: /var/ontrack/data
            {{- if .Values.ontrack.casc.enabled }}
            {{- if .Values.ontrack.casc.map }}
            - name: casc
              mountPath: "{{ .Values.ontrack.casc.directory }}/map"
            {{- end }}
            {{- if .Values.ontrack.casc.secret }}
            - name: casc-secret
              mountPath: "{{ .Values.ontrack.casc.directory }}/secret"
            {{- end }}
            {{- end }}
            {{- if eq .Values.ontrack.config.key_store "secret" }}
            - name: ontrack-key-store
              mountPath: {{ .Values.ontrack.config.secret_key_store.directory | quote }}
              readOnly: true
            {{- end }}
            {{- range $secret := .Values.ontrack.casc.secrets.names }}
            - name: {{ $secret | quote }}
              mountPath: "{{ $.Values.ontrack.casc.secrets.directory }}/{{ $secret }}"
              readOnly: true
            {{- end }}
            {{- if .Values.ontrack.application_yaml }}
            - name: application-yaml
              mountPath: /var/ontrack/config
              readOnly: true
            {{- end }}
          env:
            ########################################
            # General configuration
            ########################################
            - name: ONTRACK_CONFIG_URL
              value: {{ .Values.ontrack.url | quote }}
            - name: PROFILE
              value: {{ .Values.ontrack.profiles | quote }}
            ########################################
            # Command line arguments
            ########################################
            {{- if .Values.ontrack.args }}
            - name: ONTRACK_ARGS_GENERIC
              value: {{ .Values.ontrack.args | quote }}
            {{- else }}
            - name: ONTRACK_ARGS_GENERIC
              value: ""
            {{- end }}
            ########################################
            # List of config files locations
            ########################################
            {{- if .Values.ontrack.config_locations }}
            - name: ONTRACK_ARGS_LOCATIONS
              # The default Ontrack configuration must be taken into account
              value: "--spring.config.location=classpath:/config/application.yml,{{ .Values.ontrack.config_locations | join "," }}"
            {{- else }}
            - name: ONTRACK_ARGS_LOCATIONS
              value: ""
            {{- end}}
            ########################################
            # Application properties
            ########################################
            {{- if .Values.ontrack.application_yaml }}
            - name: ONTRACK_ARGS_CONFIG
              value: "--spring.config.location=classpath:/config/application.yml,/var/ontrack/config/application.yaml"
            {{- else }}
            - name: ONTRACK_ARGS_CONFIG
              value: ""
            {{- end }}
            ########################################
            # All command line argument
            ########################################
            - name: ONTRACK_ARGS
              value: "$(ONTRACK_ARGS_GENERIC) $(ONTRACK_ARGS_LOCATIONS) $(ONTRACK_ARGS_CONFIG)"
            ########################################
            # Database configuration
            ########################################
            {{- if .Values.postgresql.local }}
            # For test service
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ .Release.Name }}-postgresql-headless:5432/ontrack"
            # For a managed database, using external environment variables
            {{- else if .Values.postgresql.postgresFromEnv }}
            # Nothing to be declared here
            {{- else }}
            # For a managed database, using the URL
            - name: SPRING_DATASOURCE_URL
              value: {{ required "When local Postgres service is disabled, the postgresql.postgresqlUrl value must be set" .Values.postgresql.postgresqlUrl | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.postgresql.postgresqlUsername | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword | quote }}
            {{- end }}
            ########################################
            # Key management
            ########################################
            - name: ONTRACK_CONFIG_KEY_STORE
              value: {{ .Values.ontrack.config.key_store | quote }}
            {{- if eq .Values.ontrack.config.key_store "secret" }}
            - name: ONTRACK_CONFIG_FILE_KEY_STORE_DIRECTORY
              value: {{ .Values.ontrack.config.secret_key_store.directory | quote }}
            {{- end }}
            ########################################
            # Elasticsearch configuration
            ########################################
            - name: SPRING_ELASTICSEARCH_URIS
              value: "http://{{ .Values.elasticsearch.masterService }}-headless:9200"
            ########################################
            # RabbitMQ configuration
            ########################################
            - name: SPRING_RABBITMQ_HOST
              value: "{{ .Release.Name }}-rabbitmq-headless"
            - name: SPRING_RABBITMQ_USERNAME
              value: {{ .Values.rabbitmq.auth.username | quote }}
            - name: SPRING_RABBITMQ_PASSWORD
              value: {{ .Values.rabbitmq.auth.password | quote }}
            ########################################
            # Metrics tags
            ########################################
            - name: MANAGEMENT_METRICS_TAGS_APPLICATION
              value: {{ .Values.ontrack.management.metrics.tags.application | quote }}
            - name: MANAGEMENT_METRICS_TAGS_APPLICATION_INSTANCE
              value: {{ .Values.ontrack.management.metrics.tags.application_instance | quote }}
            ########################################
            # Casc
            ########################################
            {{- if .Values.ontrack.casc.enabled }}
            - name: ONTRACK_CONFIG_CASC_ENABLED
              value: "true"
            {{- if and .Values.ontrack.casc.map .Values.ontrack.casc.secret }}
            - name: ONTRACK_CONFIG_CASC_LOCATIONS
              value: "file://{{ .Values.ontrack.casc.directory }}/map,file://{{ .Values.ontrack.casc.directory }}/secret"
            {{- else if .Values.ontrack.casc.map }}
            - name: ONTRACK_CONFIG_CASC_LOCATIONS
              value: "file://{{ .Values.ontrack.casc.directory }}/map"
            {{- else if .Values.ontrack.casc.secret }}
            - name: ONTRACK_CONFIG_CASC_LOCATIONS
              value: "file://{{ .Values.ontrack.casc.directory }}/secret"
            {{- end }}
            {{- if .Values.ontrack.casc.reloading.enabled }}
            - name: ONTRACK_CONFIG_CASC_RELOADING_ENABLED
              value: "true"
            - name: ONTRACK_CONFIG_CASC_RELOADING_CRON
              value: {{ .Values.ontrack.casc.reloading.cron | quote }}
            {{- end }}
            {{- end }}
            - name: ONTRACK_CONFIG_CASC_SECRETS_TYPE
              value: {{ .Values.ontrack.casc.secrets.mapping | quote }}
            - name: ONTRACK_CONFIG_CASC_SECRETS_DIRECTORY
              value: {{ .Values.ontrack.casc.secrets.directory | quote }}
            ########################################
            # License management
            ########################################
            - name: ONTRACK_CONFIG_LICENSE_PROVIDER
              value: {{ .Values.ontrack.config.license.type | quote }}
            {{ if eq .Values.ontrack.config.license.type "stripe" }}
            - name: ONTRACK_CONFIG_LICENSE_STRIPE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ontrack.config.license.stripe.secret | quote }}
                  key: {{ .Values.ontrack.config.license.stripe.token_key_name | quote }}
            - name: ONTRACK_CONFIG_LICENSE_STRIPE_SUBSCRIPTION
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ontrack.config.license.stripe.secret | quote }}
                  key: {{ .Values.ontrack.config.license.stripe.subscription_key_name | quote }}
            {{- end }}
            ########################################
            # Arbitrary environment variables
            ########################################
            {{- with .Values.ontrack.env }}
            {{- . | toYaml | trim | nindent 12 }}
            {{- end }}
          envFrom:
          {{- range .Values.ontrack.extraConfig.secrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- range .Values.ontrack.extraConfig.configmaps }}
            - configMapRef:
                name: {{ . }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: mgt
              containerPort: 8800
              protocol: TCP
          resources: {{ toYaml .Values.ontrack.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /manage/health/liveness
              port: mgt
            failureThreshold: 3
            periodSeconds: 60
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /manage/health/readiness
              port: mgt
            failureThreshold: 3
            periodSeconds: 60
            initialDelaySeconds: 60
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: ontrack
          {{- if .Values.ontrack.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "ontrack.fullname" . }}
          {{- else }}
          emptyDir: {{- toYaml .Values.emptyDir | nindent 12 }}
          {{- end  }}
        {{- if eq .Values.ontrack.config.key_store "secret" }}
        - name: ontrack-key-store
          secret:
            secretName: {{ .Values.ontrack.config.secret_key_store.secret_name | quote }}
            optional: false
        {{- end }}
        {{- if and .Values.ontrack.casc.enabled .Values.ontrack.casc.map }}
        - name: casc
          configMap:
            name: {{ .Values.ontrack.casc.map | quote }}
            optional: false
        {{- end }}
        {{- if and .Values.ontrack.casc.enabled .Values.ontrack.casc.secret }}
        - name: casc-secret
          secret:
            secretName: {{ .Values.ontrack.casc.secret | quote }}
            optional: false
        {{- end }}
        {{- range .Values.ontrack.casc.secrets.names }}
        - name: {{ . | quote }}
          secret:
            secretName: {{ . | quote }}
            optional: false
        {{- end }}
        {{- if .Values.ontrack.application_yaml }}
        - name: application-yaml
          configMap:
            name: {{ include "ontrack.fullname" . }}-application
            optional: false
        {{- end }}
