apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ontrack.fullname" . }}
  labels:
    {{- include "ontrack.labels" . | nindent 4 }}
spec:
  serviceName: ontrack
  selector:
    matchLabels:
      {{- include "ontrack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ontrack.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ontrack.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /var/ontrack/data
              name: ontrack
          env:
            ########################################
            # General configuration
            ########################################
            - name: PROFILE
              value: {{ .Values.ontrack.profiles | quote }}
            ########################################
            # Database configuration
            ########################################
            {{- if .Values.postgresql.local }}
            # For test service
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ .Release.Name }}-postgresql-headless:5432/ontrack"
            {{- else }}
            # For a managed database
            - name: SPRING_DATASOURCE_URL
              value: {{ required "When local Postgres service is disabled, the postgresql.postgresqlUrl value must be set" .Values.postgresql.postgresqlUrl | quote }}
            {{- end }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.postgresql.postgresqlUsername | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword | quote }}
            ########################################
            # Elasticsearch configuration
            ########################################
            - name: SPRING_ELASTICSEARCH_REST_URIS
              value: "http://{{ .Values.elasticsearch.masterService }}-headless:9200"
            ########################################
            # RabbitMQ configuration
            ########################################
            - name: SPRING_RABBITMQ_HOST
              value: "{{ .Release.Name }}-rabbitmq-headless"
            - name: SPRING_RABBITMQ_USERNAME
              value: {{ .Values.rabbitmq.auth.username | quote }}
            - name: SPRING_RABBITMQ_PASSWORD
              value: {{ .Values.rabbitmq.auth.password | quote }}
            ########################################
            # Metrics tags
            ########################################
            - name: MANAGEMENT_METRICS_TAGS_APPLICATION
              value: {{ .Values.ontrack.management.metrics.tags.application | quote }}
            - name: MANAGEMENT_METRICS_TAGS_APPLICATION_INSTANCE
              value: {{ .Values.ontrack.management.metrics.tags.instance | quote }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: mgt
              containerPort: 8800
              protocol: TCP
          resources:
            {{ toYaml .Values.ontrack.resources | indent 12 }}
          livenessProbe:
            httpGet:
              path: /manage/health/liveness
              port: mgt
            failureThreshold: 3
            periodSeconds: 60
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /manage/health/readiness
              port: mgt
            failureThreshold: 3
            periodSeconds: 60
            initialDelaySeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: ontrack
          {{- if .Values.ontrack.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "ontrack.fullname" . }}
          {{- else }}
          emptyDir: {{- toYaml .Values.emptyDir | nindent 12 }}
          {{- end  }}
