{{- if and .Values.auth.keycloak.enabled (not .Values.auth.keycloak.external.enabled) .Values.auth.keycloak.settings.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ontrack.fullname" . }}-keycloak-cm
data:
  ontrack.json: |-
    {
      "id": "{{ .Values.auth.keycloak.realm }}",
      "realm": "{{ .Values.auth.keycloak.realm }}",
      "enabled": true,
      "registrationAllowed": {{ .Values.auth.keycloak.settings.registrationAllowed }},
      "resetPasswordAllowed": {{ .Values.auth.keycloak.settings.resetPasswordAllowed }},
      "users": [
        {
          "username": "{{ .Values.auth.keycloak.settings.admin.username }}",
          "enabled": true,
          "email": "{{ .Values.auth.keycloak.settings.admin.email }}",
          "firstName": "{{ .Values.auth.keycloak.settings.admin.firstName }}",
          "lastName": "{{ .Values.auth.keycloak.settings.admin.lastName }}",
          "emailVerified": true,
          "credentials": [
            {
              "type": "password",
              "value": "{{ .Values.auth.keycloak.settings.admin.password }}"
            }
          ]
        }
      ],
      "clients": [
        {
          "clientId": "{{ .Values.auth.keycloak.client.id }}",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": false,
          "baseUrl": "{{ .Values.ontrack.url }}",
          "redirectUris": [
            "{{ .Values.ontrack.url }}/api/auth/callback/keycloak"
          ],
          "webOrigins": [
            "{{ .Values.ontrack.url }}"
          ],
          "directAccessGrantsEnabled": true,
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "serviceAccountsEnabled": false,
          "authorizationServicesEnabled": false,
          "clientAuthenticatorType": "client-secret",
          "secret": "{{ .Values.auth.keycloak.client.secret }}"
        }
      ]
    }
{{- end }}
