apiVersion: v1
kind: Service
metadata:
  name: "{{ include "ontrack.fullname" . }}-management"
  labels:
    {{- include "ontrack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.management.service.type }}
  ports:
    - port: {{ .Values.management.service.port }}
      targetPort: 8800
      protocol: TCP
      name: http
  selector:
    {{- include "ontrack.selectorLabels" . | nindent 4 }}
