apiVersion: v1
kind: Service
metadata:
  name: {{ include "ontrack.fullname" . }}
  labels:
    {{- include "ontrack.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
    - port: {{ .Values.management.service.port }}
      targetPort: 8800
      protocol: TCP
      name: http
  selector:
    {{- include "ontrack.selectorLabels" . | nindent 4 }}
