{{- if .Values.management.service.specific }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ontrack.fullname" . }}-management
  labels:
    {{- include "ontrack.labels" . | nindent 4 }}
  {{- with .Values.management.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.management.service.type }}
  ports:
    - port: {{ .Values.management.service.port }}
      targetPort: 8800
      protocol: TCP
      name: mgt
  selector:
    {{- include "ontrack.selectorLabels" . | nindent 4 }}
{{- end }}