{{- if .Values.auth.next.secret.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-ui-next-auth-external-secret
spec:
  refreshInterval: {{ .Values.auth.next.secret.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.auth.next.secret.externalSecret.store.name | quote }}
    kind: {{ .Values.auth.next.secret.externalSecret.store.kind }}
  target:
    name: {{ .Values.auth.next.secret.name }}
  data:
    - secretKey: secret
      remoteRef:
        key: {{ .Values.auth.next.secret.externalSecret.store.path | quote }}
        property: secret
{{- end }}
