# Deployment of the Next UI service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ontrack.fullname" . }}-ui
  labels:
    {{- include "ontrack.labels.ui" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.ontrack.ui.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "ontrack.selectorLabels.ui" . | nindent 4 }}
